import react, { useEffect, useState } from "react" 

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLink } from "@fortawesome/free-solid-svg-icons";

function Repositories({username, userData}){
    const [repo, setRepo] = useState([]);

    useEffect(()=>{
        async function dataFetch(userData){
            const response = await fetch(userData.repos_url);
            const data = await response.json();
            console.log(data);
            setRepo(data);
        }
        dataFetch(userData);

    }, [userData]);

    console.log(repo);

    return(
        <div className="flex flex-col items-center rounded-xl bg-white p-6 shadow-lg outline outline-black/5 w-full">
            <h2 className="text-2xl text-neutral-950">Repositories</h2>
            <div className="grid grid-cols-4 gap-6 w-full mt-6">
                {repo.map((repos)=>(
                    <div key={repos.id} className="group flex flex-col gap-3 p-4 rounded-xl outline outline-black/10 items-center text-sm ">
                        <a href={repos.html_url} target="_blank" className="flex items-center justify-center bg-white text-black px-3 py-1 rounded-md hover:bg-neutral-200"><h2 className="text-lg text-black font-semibold text-center">{repos.name}</h2></a>
                        <div className="w-full p-3 rounded-lg bg-white text-black outline outline-black/10 min-h-[80px] flex items-center justify-center text-center text-xs">{repos.description}</div>
                        <div className="flex w-full gap-2 items-center">
                            <div className="flex-1 text-[10px] flex flex-wrap items-center justify-center"><Language link={repos.languages_url}/></div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
    /*<div className="group flex flex-col p-8 rounded-xl outline outline-black/5 items-center text-[1rem] m-[5%] w-fit h-[40%] hover:bg-neutral-950 hover:text-neutral-50 transition">
                        <h2 className="text-[2rem] ">{repos.name}</h2>
                        <p className="flex flex-wrap p-2 rounded-xl bg-white flex-row h-[10vh] m-0 outline outline-black/5 items-center">{repos.description}</p>
                        <div>
                            <Language link={repos.languages_url} />
                            <a href=""></a>
                        </div>

                    </div>*/
                    
                    
            
}

export default Repositories;

function Language({link}){
    const [data, setData] = useState({});

    useEffect(()=>{
        async function fetchData(link){
             const response = await fetch(link);
             const result = await response.json();

             setData(result);
        }
        fetchData(link);
    }, [link]);

    return(
        <div className="languages">
            {Object.keys(data).map(key =>{
                return(
                    <span>{key}</span>
                );
            })}
        </div>
    );
}

/*
[
  {
    "id": 1065102069,
    "node_id": "R_kgDOP3wq9Q",
    "name": "dictionary",
    "full_name": "Phoenix2066/dictionary",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/dictionary",
    "description": "A Simple Dictionary implemented using API calls",
    "fork": false,
    "url": "https://api.github.com/repos/Phoenix2066/dictionary",
    "forks_url": "https://api.github.com/repos/Phoenix2066/dictionary/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/dictionary/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/dictionary/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/dictionary/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/dictionary/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/dictionary/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/dictionary/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/dictionary/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/dictionary/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/dictionary/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/dictionary/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/dictionary/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/dictionary/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/dictionary/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/dictionary/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/dictionary/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/dictionary/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/dictionary/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/dictionary/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/dictionary/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/dictionary/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/dictionary/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/dictionary/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/dictionary/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/dictionary/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/dictionary/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/dictionary/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/dictionary/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/dictionary/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/dictionary/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/dictionary/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/dictionary/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/dictionary/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/dictionary/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/dictionary/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/dictionary/deployments",
    "created_at": "2025-09-27T04:18:30Z",
    "updated_at": "2025-09-27T12:16:22Z",
    "pushed_at": "2025-09-27T12:16:19Z",
    "git_url": "git://github.com/Phoenix2066/dictionary.git",
    "ssh_url": "git@github.com:Phoenix2066/dictionary.git",
    "clone_url": "https://github.com/Phoenix2066/dictionary.git",
    "svn_url": "https://github.com/Phoenix2066/dictionary",
    "homepage": null,
    "size": 5,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1064863199,
    "node_id": "R_kgDOP3iF3w",
    "name": "FoodPicGenerator",
    "full_name": "Phoenix2066/FoodPicGenerator",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/FoodPicGenerator",
    "description": "A simple HTML, CSS and JavaScript code for generating images of food dishes from a list.",
    "fork": false,
    "url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator",
    "forks_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/FoodPicGenerator/deployments",
    "created_at": "2025-09-26T17:07:51Z",
    "updated_at": "2025-09-27T02:04:28Z",
    "pushed_at": "2025-09-27T02:04:24Z",
    "git_url": "git://github.com/Phoenix2066/FoodPicGenerator.git",
    "ssh_url": "git@github.com:Phoenix2066/FoodPicGenerator.git",
    "clone_url": "https://github.com/Phoenix2066/FoodPicGenerator.git",
    "svn_url": "https://github.com/Phoenix2066/FoodPicGenerator",
    "homepage": null,
    "size": 6,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1154527300,
    "node_id": "R_kgDORNCwRA",
    "name": "gitx",
    "full_name": "Phoenix2066/gitx",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/gitx",
    "description": "A TUI git helper, like lazygit",
    "fork": true,
    "url": "https://api.github.com/repos/Phoenix2066/gitx",
    "forks_url": "https://api.github.com/repos/Phoenix2066/gitx/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/gitx/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/gitx/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/gitx/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/gitx/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/gitx/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/gitx/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/gitx/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/gitx/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/gitx/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/gitx/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/gitx/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/gitx/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/gitx/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/gitx/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/gitx/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/gitx/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/gitx/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/gitx/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/gitx/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/gitx/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/gitx/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/gitx/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/gitx/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/gitx/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/gitx/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/gitx/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/gitx/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/gitx/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/gitx/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/gitx/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/gitx/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/gitx/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/gitx/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/gitx/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/gitx/deployments",
    "created_at": "2026-02-10T13:44:59Z",
    "updated_at": "2026-02-20T00:11:42Z",
    "pushed_at": "2026-02-20T00:17:45Z",
    "git_url": "git://github.com/Phoenix2066/gitx.git",
    "ssh_url": "git@github.com:Phoenix2066/gitx.git",
    "clone_url": "https://github.com/Phoenix2066/gitx.git",
    "svn_url": "https://github.com/Phoenix2066/gitx",
    "homepage": "https://gitxtui.github.io/docs/",
    "size": 312,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Go",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 1114566510,
    "node_id": "R_kgDOQm7vbg",
    "name": "HackSync",
    "full_name": "Phoenix2066/HackSync",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/HackSync",
    "description": "A go to platform for hackathon participants.",
    "fork": false,
    "url": "https://api.github.com/repos/Phoenix2066/HackSync",
    "forks_url": "https://api.github.com/repos/Phoenix2066/HackSync/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/HackSync/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/HackSync/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/HackSync/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/HackSync/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/HackSync/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/HackSync/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/HackSync/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/HackSync/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/HackSync/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/HackSync/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/HackSync/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/HackSync/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/HackSync/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/HackSync/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/HackSync/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/HackSync/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/HackSync/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/HackSync/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/HackSync/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/HackSync/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/HackSync/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/HackSync/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/HackSync/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/HackSync/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/HackSync/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/HackSync/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/HackSync/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/HackSync/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/HackSync/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/HackSync/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/HackSync/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/HackSync/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/HackSync/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/HackSync/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/HackSync/deployments",
    "created_at": "2025-12-11T14:59:47Z",
    "updated_at": "2025-12-11T14:59:52Z",
    "pushed_at": "2025-12-11T15:06:28Z",
    "git_url": "git://github.com/Phoenix2066/HackSync.git",
    "ssh_url": "git@github.com:Phoenix2066/HackSync.git",
    "clone_url": "https://github.com/Phoenix2066/HackSync.git",
    "svn_url": "https://github.com/Phoenix2066/HackSync",
    "homepage": null,
    "size": 98,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1077640104,
    "node_id": "R_kgDOQDt7qA",
    "name": "HyperLiquidMCP",
    "full_name": "Phoenix2066/HyperLiquidMCP",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/HyperLiquidMCP",
    "description": "An MCP Server for HyperLiquid",
    "fork": false,
    "url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP",
    "forks_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/HyperLiquidMCP/deployments",
    "created_at": "2025-10-16T14:26:57Z",
    "updated_at": "2025-10-31T15:23:10Z",
    "pushed_at": "2025-10-22T02:41:38Z",
    "git_url": "git://github.com/Phoenix2066/HyperLiquidMCP.git",
    "ssh_url": "git@github.com:Phoenix2066/HyperLiquidMCP.git",
    "clone_url": "https://github.com/Phoenix2066/HyperLiquidMCP.git",
    "svn_url": "https://github.com/Phoenix2066/HyperLiquidMCP",
    "homepage": "",
    "size": 24,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main"
  },
  {
    "id": 1161239474,
    "node_id": "R_kgDORTcbsg",
    "name": "odin-recipes",
    "full_name": "Phoenix2066/odin-recipes",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/odin-recipes",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Phoenix2066/odin-recipes",
    "forks_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/odin-recipes/deployments",
    "created_at": "2026-02-18T22:15:29Z",
    "updated_at": "2026-02-18T22:15:36Z",
    "pushed_at": "2026-02-18T22:15:30Z",
    "git_url": "git://github.com/Phoenix2066/odin-recipes.git",
    "ssh_url": "git@github.com:Phoenix2066/odin-recipes.git",
    "clone_url": "https://github.com/Phoenix2066/odin-recipes.git",
    "svn_url": "https://github.com/Phoenix2066/odin-recipes",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1049098716,
    "node_id": "R_kgDOPof53A",
    "name": "TicTacToe",
    "full_name": "Phoenix2066/TicTacToe",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/TicTacToe",
    "description": "A simple game of Tic Tac Toe using HTML, CSS and Javascript",
    "fork": false,
    "url": "https://api.github.com/repos/Phoenix2066/TicTacToe",
    "forks_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/TicTacToe/deployments",
    "created_at": "2025-09-02T13:38:18Z",
    "updated_at": "2025-09-02T15:02:40Z",
    "pushed_at": "2025-09-02T15:02:37Z",
    "git_url": "git://github.com/Phoenix2066/TicTacToe.git",
    "ssh_url": "git@github.com:Phoenix2066/TicTacToe.git",
    "clone_url": "https://github.com/Phoenix2066/TicTacToe.git",
    "svn_url": "https://github.com/Phoenix2066/TicTacToe",
    "homepage": null,
    "size": 7,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1174944690,
    "node_id": "R_kgDORgg7sg",
    "name": "yetAnotherGitAnalyser",
    "full_name": "Phoenix2066/yetAnotherGitAnalyser",
    "private": false,
    "owner": {
      "login": "Phoenix2066",
      "id": 210047823,
      "node_id": "U_kgDODIUTTw",
      "avatar_url": "https://avatars.githubusercontent.com/u/210047823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Phoenix2066",
      "html_url": "https://github.com/Phoenix2066",
      "followers_url": "https://api.github.com/users/Phoenix2066/followers",
      "following_url": "https://api.github.com/users/Phoenix2066/following{/other_user}",
      "gists_url": "https://api.github.com/users/Phoenix2066/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Phoenix2066/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Phoenix2066/subscriptions",
      "organizations_url": "https://api.github.com/users/Phoenix2066/orgs",
      "repos_url": "https://api.github.com/users/Phoenix2066/repos",
      "events_url": "https://api.github.com/users/Phoenix2066/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Phoenix2066/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/Phoenix2066/yetAnotherGitAnalyser",
    "description": "Yet another github account analyser.",
    "fork": false,
    "url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser",
    "forks_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/forks",
    "keys_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/teams",
    "hooks_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/hooks",
    "issue_events_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/events",
    "assignees_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/tags",
    "blobs_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/languages",
    "stargazers_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/stargazers",
    "contributors_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/contributors",
    "subscribers_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/subscribers",
    "subscription_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/subscription",
    "commits_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/merges",
    "archive_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/downloads",
    "issues_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/labels{/name}",
    "releases_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Phoenix2066/yetAnotherGitAnalyser/deployments",
    "created_at": "2026-03-07T02:51:09Z",
    "updated_at": "2026-03-07T02:51:13Z",
    "pushed_at": "2026-03-07T02:51:10Z",
    "git_url": "git://github.com/Phoenix2066/yetAnotherGitAnalyser.git",
    "ssh_url": "git@github.com:Phoenix2066/yetAnotherGitAnalyser.git",
    "clone_url": "https://github.com/Phoenix2066/yetAnotherGitAnalyser.git",
    "svn_url": "https://github.com/Phoenix2066/yetAnotherGitAnalyser",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  }
]

*/